// Auto-generated by generateAuxABI.ts
export const auxAbi = [
  {
    "type": "impl",
    "name": "AuxContract",
    "interface_name": "carmine_protocol::aux_contract::IAuxContract"
  },
  {
    "type": "enum",
    "name": "core::bool",
    "variants": [
      {
        "name": "False",
        "type": "()"
      },
      {
        "name": "True",
        "type": "()"
      }
    ]
  },
  {
    "type": "struct",
    "name": "cubit::f128::types::fixed::Fixed",
    "members": [
      {
        "name": "mag",
        "type": "core::integer::u128"
      },
      {
        "name": "sign",
        "type": "core::bool"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::option_::Option_",
    "members": [
      {
        "name": "option_side",
        "type": "core::integer::u8"
      },
      {
        "name": "maturity",
        "type": "core::integer::u64"
      },
      {
        "name": "strike_price",
        "type": "cubit::f128::types::fixed::Fixed"
      },
      {
        "name": "quote_token_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "base_token_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "option_type",
        "type": "core::integer::u8"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::option_::OptionWithPremia",
    "members": [
      {
        "name": "option",
        "type": "carmine_protocol::types::option_::Option_"
      },
      {
        "name": "premia",
        "type": "cubit::f128::types::fixed::Fixed"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::integer::u256",
    "members": [
      {
        "name": "low",
        "type": "core::integer::u128"
      },
      {
        "name": "high",
        "type": "core::integer::u128"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::pool::Pool",
    "members": [
      {
        "name": "quote_token_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "base_token_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "option_type",
        "type": "core::integer::u8"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::pool::PoolInfo",
    "members": [
      {
        "name": "pool",
        "type": "carmine_protocol::types::pool::Pool"
      },
      {
        "name": "lptoken_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "staked_capital",
        "type": "core::integer::u256"
      },
      {
        "name": "unlocked_capital",
        "type": "core::integer::u256"
      },
      {
        "name": "value_of_pool_position",
        "type": "cubit::f128::types::fixed::Fixed"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::pool::UserPoolInfo",
    "members": [
      {
        "name": "value_of_user_stake",
        "type": "core::integer::u256"
      },
      {
        "name": "size_of_users_tokens",
        "type": "core::integer::u256"
      },
      {
        "name": "pool_info",
        "type": "carmine_protocol::types::pool::PoolInfo"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::pool::PoolState",
    "members": [
      {
        "name": "locked",
        "type": "core::integer::u256"
      },
      {
        "name": "unlocked",
        "type": "core::integer::u256"
      },
      {
        "name": "balance",
        "type": "core::integer::u256"
      },
      {
        "name": "position",
        "type": "cubit::f128::types::fixed::Fixed"
      },
      {
        "name": "value",
        "type": "core::integer::u256"
      },
      {
        "name": "lp_address",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::option_::OptionWithAddress",
    "members": [
      {
        "name": "option_side",
        "type": "core::integer::u8"
      },
      {
        "name": "maturity",
        "type": "core::integer::u64"
      },
      {
        "name": "strike_price",
        "type": "cubit::f128::types::fixed::Fixed"
      },
      {
        "name": "address",
        "type": "core::starknet::contract_address::ContractAddress"
      }
    ]
  },
  {
    "type": "struct",
    "name": "carmine_protocol::types::price::Price",
    "members": [
      {
        "name": "token_address",
        "type": "core::starknet::contract_address::ContractAddress"
      },
      {
        "name": "price",
        "type": "core::integer::u128"
      }
    ]
  },
  {
    "type": "interface",
    "name": "carmine_protocol::aux_contract::IAuxContract",
    "items": [
      {
        "type": "function",
        "name": "get_all_non_expired_options_with_premia",
        "inputs": [
          {
            "name": "lpt_addr",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "core::array::Array::<carmine_protocol::types::option_::OptionWithPremia>"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_user_pool_info",
        "inputs": [
          {
            "name": "user",
            "type": "core::starknet::contract_address::ContractAddress"
          },
          {
            "name": "lpt_addr",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "carmine_protocol::types::pool::UserPoolInfo"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_pool_state",
        "inputs": [
          {
            "name": "lpt_addr",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "carmine_protocol::types::pool::PoolState"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_all_pools_states",
        "inputs": [],
        "outputs": [
          {
            "type": "core::array::Array::<carmine_protocol::types::pool::PoolState>"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_pool_options_with_address",
        "inputs": [
          {
            "name": "lpt_addr",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "core::array::Array::<carmine_protocol::types::option_::OptionWithAddress>"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_price",
        "inputs": [
          {
            "name": "token_address",
            "type": "core::starknet::contract_address::ContractAddress"
          }
        ],
        "outputs": [
          {
            "type": "carmine_protocol::types::price::Price"
          }
        ],
        "state_mutability": "view"
      },
      {
        "type": "function",
        "name": "get_all_token_prices",
        "inputs": [],
        "outputs": [
          {
            "type": "core::array::Array::<carmine_protocol::types::price::Price>"
          }
        ],
        "state_mutability": "view"
      }
    ]
  },
  {
    "type": "event",
    "name": "carmine_protocol::aux_contract::AuxContract::Event",
    "kind": "enum",
    "variants": []
  }
] as const;
