import { initSdk } from "../src/core/config";
import { AUX_ADDRESS } from "../src/core/constants";
import { getProvider } from "../src/core/provider";

initSdk();

async function generateAuxABI() {
  const provider = getProvider();
  const { abi } = await provider.getClassAt(AUX_ADDRESS);

  // console output is captured into a file
  console.log(`// Auto-generated by generateAuxABI.ts
export const auxAbi = ${JSON.stringify(abi, null, 2)} as const;
`);
}

generateAuxABI();
