import { Abi } from "starknet";
import { initSdk } from "../src/core/config";
import { getProvider } from "../src/core/provider";
import { AMM_ADDRESS, AUX_ADDRESS } from "../src/core/constants";

initSdk();

async function generateAmmABI() {
  const provider = getProvider();
  const { abi } = await provider.getClassAt(AMM_ADDRESS);

  // console output is captured into a file
  // just run pnpm generate-abi
  console.log(`// Auto-generated by generateAmmABI.ts
export const ammAbi = ${JSON.stringify(abi, null, 2)} as const;
`);
}

generateAmmABI();
