import { initSdk } from "../src/config";
import { AMM_ADDRESS, AUX_ADDRESS } from "../src/constants";
import { getProvider } from "../src/rpc/provider";

initSdk();

async function generateABI() {
  const provider = getProvider();
  const { abi: ammAbi } = await provider.getClassAt(AMM_ADDRESS);
  const { abi: auxAbi } = await provider.getClassAt(AUX_ADDRESS);

  const abi = [
    ...ammAbi,
    ...auxAbi.filter(
      (b) => !ammAbi.some((a) => a.type === b.type && a.name === b.name)
    ),
  ];

  // console output is captured into a file
  // just run pnpm generate-abi
  console.log(`// Auto-generated by generateABI.ts
export const abi = ${JSON.stringify(abi, null, 2)} as const;
`);
}

generateABI();
