import { initSdk } from "../src/config";
import { GOVERNANCE_ADDRESS } from "../src/constants";
import { getProvider } from "../src/rpc/provider";

initSdk();

async function generateGovernanceABI() {
  const provider = getProvider();
  const { abi } = await provider.getClassAt(GOVERNANCE_ADDRESS);

  // console output is captured into a file
  console.log(`// Auto-generated by generateGovernanceABI.ts
export const governanceAbi = ${JSON.stringify(abi, null, 2)} as const;
`);
}

generateGovernanceABI();
