import { ETH_ADDRESS } from "starknet";
import { initSdk } from "../src/core/config";
import { getProvider } from "../src/core/provider";

initSdk();

async function generateErc20ABI() {
  const provider = getProvider();
  const { abi } = await provider.getClassAt(ETH_ADDRESS);

  // console output is captured into a file
  console.log(`// Auto-generated by generateErc20ABI.ts
export const erc20Abi = ${JSON.stringify(abi, null, 2)} as const;
`);
}

generateErc20ABI();
